services:
  report_service:
    container_name: report_service
    image: report_service
    build:
      context: .
      dockerfile: ReportService.GrpcService/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=User ID=postgres;Password=postgres;Host=postgresql;Port=5432;Database=postgres
    depends_on:
      - postgresql
    ports:
      - "5001:80"

  postgresql:
    container_name: postgresql
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - /D/PostgreSQL:/var/lib/postgresql/data/
    ports:
      - "5432:5432"